#n1 = int(input('digite um número: '))
#print('o seu sucessor é {} e o seu antecessor é {}'.format(n1+1,n1-1))
#print('o dobro desse numero é {}, o triplo desse numero é {}, a raiz quadrada desse é {}'.format(n1*2,n1*3,n1/(n1**(1/2))))
#n = float(input('Qual sua nota? '))
#n2 = float(input('Qual sua segunda nota? '))
#print('Sua média é : {}'.format((n+n2)/2))
#m = int(input('Quntos metros? '))
#print('convetido para centímetros: {}c'.format(m*100))
#print('convetido para milímetros: {}m'.format(m*1000))
#for n in range(1,10):
#    print(f'{n1} x {n} = {n1*n}')
#d = float(input('Quanto dindin ce tem? '))
#print(f'ce pode comprar {d/3.27:.2f} dolaris')
#l = float(input('Quaa a largura da parede? '))
#a = float(input('quaç a altura da parede? '))
#area = a * l
#l = area/2
#print(f'sera necessario {l} litros para pintar ')
#p = float(input('qual o preço do produto? '))
#print(f'o novo preço com 5% de desonto é ${p-(p*0.05)}')
#print(f'o novo preço é ${p*0.95}')
#s = float(input('o seu sálario é : '))
#print(f'o seu sálario com 15% de aumento é {s*1.15}')
#print(f'o seu sálario com 15% de aumento é {(s*0.15)+s}')
